//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PublicApiGenerator.System.CodeDom.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;Comment&apos; property of the CodeCommentStatement &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string Argument_NullComment
        {
            get
            {
                return ResourceManager.GetString("Argument_NullComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The total arity specified in &apos;{0}&apos; does not match the number of TypeArguments supplied.  There were &apos;{1}&apos; TypeArguments supplied..
        /// </summary>
        internal static string ArityDoesntMatch
        {
            get
            {
                return ResourceManager.GetString("ArityDoesntMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to auto-generated&gt;.
        /// </summary>
        internal static string AutoGen_Comment_Line1
        {
            get
            {
                return ResourceManager.GetString("AutoGen_Comment_Line1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This code was generated by a tool..
        /// </summary>
        internal static string AutoGen_Comment_Line2
        {
            get
            {
                return ResourceManager.GetString("AutoGen_Comment_Line2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Changes to this file may cause incorrect behavior and will be lost if.
        /// </summary>
        internal static string AutoGen_Comment_Line4
        {
            get
            {
                return ResourceManager.GetString("AutoGen_Comment_Line4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the code is regenerated..
        /// </summary>
        internal static string AutoGen_Comment_Line5
        {
            get
            {
                return ResourceManager.GetString("AutoGen_Comment_Line5", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is no CodeDom provider defined for the language..
        /// </summary>
        internal static string CodeDomProvider_NotDefined
        {
            get
            {
                return ResourceManager.GetString("CodeDomProvider_NotDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The output writer for code generation and the writer supplied don&apos;t match and cannot be used. This is generally caused by a bad implementation of a CodeGenerator derived class..
        /// </summary>
        internal static string CodeGenOutputWriter
        {
            get
            {
                return ResourceManager.GetString("CodeGenOutputWriter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This code generation API cannot be called while the generator is being used to generate something else..
        /// </summary>
        internal static string CodeGenReentrance
        {
            get
            {
                return ResourceManager.GetString("CodeGenReentrance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file name &apos;{0}&apos; was already in the collection..
        /// </summary>
        internal static string DuplicateFileName
        {
            get
            {
                return ResourceManager.GetString("DuplicateFileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting for a program to execute. The command being executed was {0}..
        /// </summary>
        internal static string ExecTimeout
        {
            get
            {
                return ResourceManager.GetString("ExecTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Element type {0} is not supported..
        /// </summary>
        internal static string InvalidElementType
        {
            get
            {
                return ResourceManager.GetString("InvalidElementType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string InvalidIdentifier
        {
            get
            {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The identifier:&quot;{0}&quot; on the property:&quot;{1}&quot; of type:&quot;{2}&quot; is not a valid language-independent identifier name. Check to see if CodeGenerator.IsValidLanguageIndependentIdentifier allows the identifier name..
        /// </summary>
        internal static string InvalidLanguageIdentifier
        {
            get
            {
                return ResourceManager.GetString("InvalidLanguageIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Argument {0} cannot be null or zero-length..
        /// </summary>
        internal static string InvalidNullEmptyArgument
        {
            get
            {
                return ResourceManager.GetString("InvalidNullEmptyArgument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The CodeChecksumPragma file name &apos;{0}&apos; contains invalid path characters..
        /// </summary>
        internal static string InvalidPathCharsInChecksum
        {
            get
            {
                return ResourceManager.GetString("InvalidPathCharsInChecksum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Primitive Type: {0}. Consider using CodeObjectCreateExpression..
        /// </summary>
        internal static string InvalidPrimitiveType
        {
            get
            {
                return ResourceManager.GetString("InvalidPrimitiveType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The region directive &apos;{0}&apos; contains invalid characters.  RegionText cannot contain any new line characters..
        /// </summary>
        internal static string InvalidRegion
        {
            get
            {
                return ResourceManager.GetString("InvalidRegion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type name:&quot;{0}&quot; on the property:&quot;{1}&quot; of type:&quot;{2}&quot; is not a valid language-independent type name..
        /// </summary>
        internal static string InvalidTypeName
        {
            get
            {
                return ResourceManager.GetString("InvalidTypeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This CodeDomProvider does not support this method..
        /// </summary>
        internal static string NotSupported_CodeDomAPI
        {
            get
            {
                return ResourceManager.GetString("NotSupported_CodeDomAPI", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This CodeDomProvider type does not have a constructor that takes providerOptions - &quot;{0}&quot;..
        /// </summary>
        internal static string Provider_does_not_support_options
        {
            get
            {
                return ResourceManager.GetString("Provider_does_not_support_options", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {unknown}.
        /// </summary>
        internal static string toStringUnknown
        {
            get
            {
                return ResourceManager.GetString("toStringUnknown", resourceCulture);
            }
        }
    }
}
